# Author Gianluca Frison

include ../../Makefile.rule

OBJS =

OBJS += allocate_ocp_nlp.o
OBJS += ocp_nlp_common.o
# OBJS += ocp_nlp_common_ext_dep.o
# OBJS += ocp_nlp_sm_gn.o
OBJS += ocp_nlp_gn_sqp.o
# OBJS += ocp_nlp_sqp_ext_dep.o

obj: $(OBJS)

clean:
	rm -f *.o
	rm -f *.s
