
% Dialog with which the user selects the folder where the acados libs
% reside.
if(~ exist('acados_lib_path', 'var'))
    acados_path = uigetdir('', 'Please select folder with acados libraries for dSpace');
    acados_lib_path = fullfile(acados_path, 'lib');
end

% Compile S function and link with acados
mex('-I../', ...
    '-I../../', ...
    '-I../../external', ...
    '-I../../external/blasfeo/include', ...
    ['-L', acados_lib_path], ...
    '-lacados', ...
    '-lhpmpc', ...
    '-lhpipm', ...
    '-lblasfeo', ...
    '-lqpOASES_e', ...
    '-lqpdunes', ...
    '-lqore', ...
    '-lblas', ...
    'ocp_qp_s_function.c');

mex('-g', '-I../', ...
    '-I../../', ...
    '-I../../external', ...
    '-I../../external/blasfeo/include', ...
    ['-L', acados_lib_path], ...
    '-lacados', ...
    '-lhpmpc', ...
    '-lhpipm', ...
    '-lblasfeo', ...
    '-lqpOASES_e', ...
    '-lqpdunes', ...
    '-lqore', ...
    '-lblas', ...
    'ocp_nlp_s_function.c', ...
    '../../examples/c/crane_model/vde_forw_model.c');
