# Author Gianluca Frison

include ../../Makefile.rule

OBJS =

OBJS += sim_casadi_wrapper.o
OBJS += sim_collocation.o
OBJS += sim_erk_integrator.o
OBJS += sim_common.o
OBJS += sim_lifted_irk_integrator.o
OBJS += sim_erk_integrator.o

obj: $(OBJS)

clean:
	rm -f *.o
	rm -f *.s
