#
# Copyright (c) The acados authors.
#
# This file is part of acados.
#
# Licensed under the 2-Clause BSD License.


include ../../Makefile.rule

OBJS =

OBJS += sim_collocation_utils.o
OBJS += sim_erk_integrator.o
OBJS += sim_common.o
OBJS += sim_lifted_irk_integrator.o
OBJS += sim_irk_integrator.o
OBJS += sim_gnsf.o

obj: $(OBJS)

clean:
	rm -f *.o
	rm -f *.s
