#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := app-template

include $(IDF_PATH)/make/project.mk

# CFLAGS += -D__SUPPRESSANYOUTPUT__ -D__NO_STATIC__ -D__EXTERNAL_DIMENSIONS__
CFLAGS += -D__NO_STATIC__ -D__EXTERNAL_DIMENSIONS__
CFLAGS += -Wno-unused-function -Wno-unused-parameter -Wno-implicit-function-declaration
