
dynamic_library:
	gcc -shared -o ocp_qp_data_nmasses_4_solver_HPMPC_B0.so ocp_qp_data_nmasses_4_solver_HPMPC_B0.c
	gcc -shared -o ocp_qp_data_nmasses_4_solver_HPMPC_B5.so ocp_qp_data_nmasses_4_solver_HPMPC_B5.c
	gcc -shared -o ocp_qp_data_nmasses_4_solver_HPMPC_B10.so ocp_qp_data_nmasses_4_solver_HPMPC_B10.c
