language: c
env:
  global:
    - BLASFEO_TARGET=X64_AUTOMATIC
    - HPIPM_TARGET=X64_AUTOMATIC
    - ACADOS_UNIT_TESTS="ON"
    - ACADOS_EXAMPLES="OFF"
    - ACADOS_WITH_QPOASES="ON"
    - ACADOS_LINT="OFF"
    - ACADOS_OCTAVE_TEMPLATE="OFF"
    - ACADOS_MATLAB="OFF"
    - ACADOS_OCTAVE="OFF"
    - ACADOS_PYTHON="OFF"
    - ACADOS_ON_TRAVIS="ON"

os: linux
sudo: required
dist: focal

group: travis_latest

services:
  - xvfb

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
      - deadsnakes

matrix:
  include:
    # - name: MacOS Build
    #   os: osx
    #   osx_image: xcode9.4
    #   # osx_image: xcode10.1
    #   python: 3.7
    #   env:
    #     - DEPLOY_NAME="osx-python"

    - name: Linux Gcc - Octave NO_template
      env:
        - DEPLOY_NAME="linux octave gcc"
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - ACADOS_OCTAVE="ON"
        - ACADOS_OCTAVE_TEMPLATE="OFF"
        - ACADOS_UNIT_TESTS="OFF"
        - ACADOS_WITH_QPDUNES="ON"
        - ACADOS_WITH_OSQP="ON"

    - name: Linux Gcc - Python interface
      env:
        - DEPLOY_NAME="linux python gcc"
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - ACADOS_PYTHON="ON"
        - ACADOS_UNIT_TESTS="OFF"
        - ACADOS_WITH_QPDUNES="ON"
        - ACADOS_WITH_OSQP="ON"

    - name: Linux Gcc - Octave interface + template
      env:
        - DEPLOY_NAME="linux octave gcc"
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - ACADOS_OCTAVE="ON"
        - ACADOS_OCTAVE_TEMPLATE="ON"
        - ACADOS_UNIT_TESTS="OFF"

    # - name: Linux Clang
    #   env:
    #     - DEPLOY_NAME="linux-clang"
    #     - MATRIX_EVAL="CC=clang && CXX=clang++"
    #     # - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
    #     - ACADOS_OCTAVE="OFF"
    #     - ACADOS_UNIT_TESTS="ON"
    #     - ACADOS_EXAMPLES="ON"

cache:
  ccache: true
  directories:

before_install:
  - eval "${MATRIX_EVAL}"
  - SECTION='before_install'
  - export SCRIPT_DIR="${TRAVIS_BUILD_DIR}/ci/${TRAVIS_OS_NAME}"
  - export SHARED_SCRIPT_DIR="${TRAVIS_BUILD_DIR}/ci/shared"
  - source "${SCRIPT_DIR}/dispatch.sh"
  - python --version
  - python3 --version

install:
  - SECTION='install'
  - source "${SCRIPT_DIR}/dispatch.sh"

script:
  - SECTION='script'
  - source "${SCRIPT_DIR}/dispatch.sh"

after_success:
  - SECTION='after_success'
  # - mkdir -p "${DEPLOY_FOLDER}"
  - source "${SCRIPT_DIR}/dispatch.sh"

before_deploy:
  - cd "${ACADOS_INSTALL_DIR}/lib/"
  - tar -zcf acados-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz *
  - cd ../..

deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file_glob: true
  file: "${ACADOS_INSTALL_DIR}/lib/acados-*"
  skip_cleanup: true
  on:
    tags: true
