/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) Butcher_fun_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[5] = {1, 1, 0, 1, 0};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[33] = {4, 6, 0, 4, 8, 12, 16, 20, 24, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
#define s1 CASADI_PREFIX(s1)
/* Butcher_fun */
int Butcher_fun(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=2.1740304594153345e-04;
  if (res[0]!=0) res[0][0]=a0;
  a0=4.7028347726940178e-04;
  if (res[0]!=0) res[0][1]=a0;
  a0=4.1796243615363981e-04;
  if (res[0]!=0) res[0][2]=a0;
  a0=4.4368796752447602e-04;
  if (res[0]!=0) res[0][3]=a0;
  a0=-6.6506422512548836e-05;
  if (res[0]!=0) res[0][4]=a0;
  a0=4.0757317319918871e-04;
  if (res[0]!=0) res[0][5]=a0;
  a0=8.8488171431494954e-04;
  if (res[0]!=0) res[0][6]=a0;
  a0=7.8362115590450726e-04;
  if (res[0]!=0) res[0][7]=a0;
  a0=3.1565828865578292e-05;
  if (res[0]!=0) res[0][8]=a0;
  a0=-6.9694729544863079e-05;
  if (res[0]!=0) res[0][9]=a0;
  a0=4.0761381157089830e-04;
  if (res[0]!=0) res[0][10]=a0;
  a0=8.8169340728263927e-04;
  if (res[0]!=0) res[0][11]=a0;
  a0=-8.8874522945628525e-06;
  if (res[0]!=0) res[0][12]=a0;
  a0=1.6838079076272193e-05;
  if (res[0]!=0) res[0][13]=a0;
  a0=-3.5482962039489016e-05;
  if (res[0]!=0) res[0][14]=a0;
  a0=2.1739746928837970e-04;
  if (res[0]!=0) res[0][15]=a0;
  a0=4.3479766709212888e-04;
  if (res[0]!=0) res[0][16]=a0;
  a0=8.1519700410106479e-04;
  if (res[0]!=0) res[0][17]=a0;
  a0=8.1516664295205789e-04;
  if (res[0]!=0) res[0][18]=a0;
  a0=4.3483868585474718e-04;
  if (res[0]!=0) res[0][19]=a0;
  a0=6.9430000000000006e-02;
  if (res[0]!=0) res[0][20]=a0;
  a0=3.3000000000000002e-01;
  if (res[0]!=0) res[0][21]=a0;
  a0=6.6998999999999997e-01;
  if (res[0]!=0) res[0][22]=a0;
  a0=9.3056000000000005e-01;
  if (res[0]!=0) res[0][23]=a0;
  return 0;
}

void Butcher_fun_incref(void) {
}

void Butcher_fun_decref(void) {
}

int Butcher_fun_n_in(void) { return 1;}

int Butcher_fun_n_out(void) { return 1;}

const char* Butcher_fun_name_in(int i){
  switch (i) {
  case 0: return "i0";
  default: return 0;
  }
}

const char* Butcher_fun_name_out(int i){
  switch (i) {
  case 0: return "o0";
  default: return 0;
  }
}

const int* Butcher_fun_sparsity_in(int i) {
  switch (i) {
  case 0: return s0;
  default: return 0;
  }
}

const int* Butcher_fun_sparsity_out(int i) {
  switch (i) {
  case 0: return s1;
  default: return 0;
  }
}

int Butcher_fun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
