message(STATUS "DSPACE")

find_program(CMAKE_MAKE_PROGRAM ${DSPACE_TOOLS}/Exe/DSMAKE.EXE)

set(CMAKE_MAKE_PROGRAM ${CMAKE_MAKE_PROGRAM})

set(CMAKE_INCLUDE_FLAG_C "-J")
set(CMAKE_INCLUDE_FLAG_CXX "-J")