
% Dialog with which the user selects the folder where the acados libs
% reside.
if(~ exist('acados_lib_path', 'var'))
    acados_lib_path = uigetdir('', 'Please select folder with acados libraries for dSpace');
end

% Compile S function and link with acados
mex('-I../', ...
    '-I../../', ...
    '-I../../external', ...
    '-I../../external/blasfeo/include', ...
    ['-L', acados_lib_path/lib], ...
    '-lacados', ...
    '-lblasfeo', ...
    '-lhpipm', ...
    '-lqpOASES_e', ...
    '-lqpdunes', ...
    'ocp_qp_s_function.c');