# Author Gianluca Frison

include ../../Makefile.rule

OBJS =

OBJS += math.o
OBJS += copy.o
OBJS += print.o
OBJS += timing.o
OBJS += mem.o
OBJS += create.o

obj: $(OBJS)

clean:
	rm -f *.o
	rm -f *.s
