#
# Copyright (c) The acados authors.
#
# This file is part of acados.
#
# Licensed under the 2-Clause BSD License.


include ../../Makefile.rule

OBJS =

OBJS += math.o
OBJS += print.o
OBJS += timing.o
OBJS += mem.o
OBJS += external_function_generic.o

obj: $(OBJS)

clean:
	rm -f *.o
	rm -f *.s
