name: 'Setup Test Environment'
description: 'Checks out the repository and downloads build artifacts (lib, build, include).'

inputs:
  artifact-name-prefix:
    description: 'The unique prefix of the artifacts to download.'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
      shell: bash

    - name: Download lib artifact
      uses: actions/download-artifact@v4
      with:
        name: lib-${{ inputs.artifact-name-prefix }}
        path: ${{ github.workspace }}/lib
      shell: bash

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-${{ inputs.artifact-name-prefix }}
        path: ${{ github.workspace }}/build
      shell: bash

    - name: Download include artifact
      uses: actions/download-artifact@v4
      with:
        name: include-${{ inputs.artifact-name-prefix }}
        path: ${{ github.workspace }}/include
      shell: bash