/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) impl_jac_x_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
#ifndef CASADI_SYMBOL_EXPORT
#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#if defined(STATIC_LINKED)
#define CASADI_SYMBOL_EXPORT
#else /* defined(STATIC_LINKED) */
#define CASADI_SYMBOL_EXPORT __declspec(dllexport)
#endif /* defined(STATIC_LINKED) */
#elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
#else /* defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__) */
#define CASADI_SYMBOL_EXPORT
#endif /* defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__) */
#endif /* CASADI_SYMBOL_EXPORT */
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[8] = {4, 1, 0, 4, 0, 1, 2, 3};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[5] = {1, 1, 0, 1, 0};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
#define s2 CASADI_PREFIX(s2)
/* impl_jacFun_x */
CASADI_SYMBOL_EXPORT int impl_jacFun_x(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  if (res[0]!=0) res[0][3]=a0;
  if (res[0]!=0) res[0][4]=a0;
  if (res[0]!=0) res[0][5]=a0;
  real_t a1=arg[0] ? arg[0][1] : 0;
  real_t a2=cos(a1);
  real_t a3=-8.0000000000000016e-02;
  a2=(a3*a2);
  real_t a4=arg[0] ? arg[0][3] : 0;
  real_t a5=sq(a4);
  a2=(a5*a2);
  real_t a6=cos(a1);
  real_t a7=9.8100000000000009e-01;
  a6=(a7*a6);
  real_t a8=cos(a1);
  a8=(a6*a8);
  real_t a9=sin(a1);
  a9=(a7*a9);
  real_t a10=sin(a1);
  a9=(a10*a9);
  a8=(a8-a9);
  a2=(a2+a8);
  a8=cos(a1);
  a9=sq(a8);
  real_t a11=1.0000000000000001e-01;
  a9=(a11*a9);
  real_t a12=1.1000000000000001e+00;
  a9=(a12-a9);
  a2=(a2/a9);
  real_t a13=sin(a1);
  a13=(a3*a13);
  a5=(a13*a5);
  real_t a14=arg[2] ? arg[2][0] : 0;
  a5=(a5+a14);
  a6=(a6*a10);
  a5=(a5+a6);
  a5=(a5/a9);
  a5=(a5/a9);
  a8=(a8+a8);
  a6=sin(a1);
  a8=(a8*a6);
  a8=(a11*a8);
  a5=(a5*a8);
  a2=(a2-a5);
  a2=(-a2);
  if (res[0]!=0) res[0][6]=a2;
  a2=cos(a1);
  a2=(a3*a2);
  a5=cos(a1);
  a5=(a2*a5);
  a8=sin(a1);
  a3=(a3*a8);
  a8=sin(a1);
  a3=(a8*a3);
  a5=(a5-a3);
  a3=sq(a4);
  a5=(a3*a5);
  a6=sin(a1);
  a6=(a14*a6);
  a5=(a5-a6);
  a6=cos(a1);
  a6=(a7*a6);
  a5=(a5+a6);
  a6=cos(a1);
  a10=9.8100000000000005e+00;
  a6=(a10*a6);
  a5=(a5+a6);
  a6=cos(a1);
  real_t a15=sq(a6);
  a15=(a11*a15);
  a12=(a12-a15);
  a15=8.0000000000000004e-01;
  a12=(a15*a12);
  a5=(a5/a12);
  a2=(a2*a8);
  a3=(a2*a3);
  a8=cos(a1);
  a14=(a14*a8);
  a3=(a3+a14);
  a14=sin(a1);
  a7=(a7*a14);
  a3=(a3+a7);
  a7=sin(a1);
  a10=(a10*a7);
  a3=(a3+a10);
  a3=(a3/a12);
  a3=(a3/a12);
  a6=(a6+a6);
  a1=sin(a1);
  a6=(a6*a1);
  a11=(a11*a6);
  a15=(a15*a11);
  a3=(a3*a15);
  a5=(a5-a3);
  a5=(-a5);
  if (res[0]!=0) res[0][7]=a5;
  a5=-1.;
  if (res[0]!=0) res[0][8]=a5;
  if (res[0]!=0) res[0][9]=a0;
  if (res[0]!=0) res[0][10]=a0;
  if (res[0]!=0) res[0][11]=a0;
  if (res[0]!=0) res[0][12]=a0;
  if (res[0]!=0) res[0][13]=a5;
  a5=(a4+a4);
  a13=(a13*a5);
  a13=(a13/a9);
  a13=(-a13);
  if (res[0]!=0) res[0][14]=a13;
  a4=(a4+a4);
  a2=(a2*a4);
  a2=(a2/a12);
  a2=(-a2);
  if (res[0]!=0) res[0][15]=a2;
  return 0;
}

CASADI_SYMBOL_EXPORT void impl_jacFun_x_incref(void) {
}

CASADI_SYMBOL_EXPORT void impl_jacFun_x_decref(void) {
}

CASADI_SYMBOL_EXPORT int impl_jacFun_x_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int impl_jacFun_x_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* impl_jacFun_x_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* impl_jacFun_x_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jacFun_x_sparsity_in(int i) {
  switch (i) {
    case 0: return s0;
    case 1: return s0;
    case 2: return s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* impl_jacFun_x_sparsity_out(int i) {
  switch (i) {
    case 0: return s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int impl_jacFun_x_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 16;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
