/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jac_model_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Printing routine */
#define PRINTF printf

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const int casadi_s1[5] = {1, 1, 0, 1, 0};
static const int casadi_s2[13] = {4, 4, 0, 0, 2, 3, 6, 2, 3, 0, 1, 2, 3};

/* jacFun:(i0[4],i1)->(o0[4],o1[4x4,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0] ? arg[0][2] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0] ? arg[0][3] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a1=-8.0000000000000016e-02;
  a2=arg[0] ? arg[0][1] : 0;
  a3=sin(a2);
  a3=(a1*a3);
  a4=sq(a0);
  a5=(a3*a4);
  a6=arg[1] ? arg[1][0] : 0;
  a5=(a5+a6);
  a7=9.8100000000000009e-01;
  a8=cos(a2);
  a8=(a7*a8);
  a9=sin(a2);
  a10=(a8*a9);
  a5=(a5+a10);
  a10=1.1000000000000001e+00;
  a11=1.0000000000000001e-01;
  a12=cos(a2);
  a13=sq(a12);
  a13=(a11*a13);
  a13=(a10-a13);
  a5=(a5/a13);
  if (res[0]!=0) res[0][2]=a5;
  a14=cos(a2);
  a14=(a1*a14);
  a15=sin(a2);
  a16=(a14*a15);
  a17=sq(a0);
  a18=(a16*a17);
  a19=cos(a2);
  a19=(a6*a19);
  a18=(a18+a19);
  a19=sin(a2);
  a19=(a7*a19);
  a18=(a18+a19);
  a19=9.8100000000000005e+00;
  a20=sin(a2);
  a20=(a19*a20);
  a18=(a18+a20);
  a20=8.0000000000000004e-01;
  a21=cos(a2);
  a22=sq(a21);
  a22=(a11*a22);
  a10=(a10-a22);
  a10=(a20*a10);
  a18=(a18/a10);
  if (res[0]!=0) res[0][3]=a18;
  a22=cos(a2);
  a22=(a1*a22);
  a4=(a4*a22);
  a22=cos(a2);
  a8=(a8*a22);
  a22=sin(a2);
  a22=(a7*a22);
  a9=(a9*a22);
  a8=(a8-a9);
  a4=(a4+a8);
  a4=(a4/a13);
  a5=(a5/a13);
  a12=(a12+a12);
  a8=sin(a2);
  a12=(a12*a8);
  a12=(a11*a12);
  a5=(a5*a12);
  a4=(a4-a5);
  if (res[1]!=0) res[1][0]=a4;
  a4=cos(a2);
  a14=(a14*a4);
  a4=sin(a2);
  a1=(a1*a4);
  a15=(a15*a1);
  a14=(a14-a15);
  a17=(a17*a14);
  a14=sin(a2);
  a6=(a6*a14);
  a17=(a17-a6);
  a6=cos(a2);
  a7=(a7*a6);
  a17=(a17+a7);
  a7=cos(a2);
  a19=(a19*a7);
  a17=(a17+a19);
  a17=(a17/a10);
  a18=(a18/a10);
  a21=(a21+a21);
  a2=sin(a2);
  a21=(a21*a2);
  a11=(a11*a21);
  a20=(a20*a11);
  a18=(a18*a20);
  a17=(a17-a18);
  if (res[1]!=0) res[1][1]=a17;
  a17=1.;
  if (res[1]!=0) res[1][2]=a17;
  if (res[1]!=0) res[1][3]=a17;
  a17=(a0+a0);
  a3=(a3*a17);
  a3=(a3/a13);
  if (res[1]!=0) res[1][4]=a3;
  a0=(a0+a0);
  a16=(a16*a0);
  a16=(a16/a10);
  if (res[1]!=0) res[1][5]=a16;
  return 0;
}

CASADI_SYMBOL_EXPORT int jacFun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void jacFun_incref(void) {
}

CASADI_SYMBOL_EXPORT void jacFun_decref(void) {
}

CASADI_SYMBOL_EXPORT int jacFun_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT int jacFun_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT const char* jacFun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jacFun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* jacFun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* jacFun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jacFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 23;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
