/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) vde_adj_model_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y

/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  #define fmin CASADI_PREFIX(fmin)
  casadi_real fmin(casadi_real x, casadi_real y) { return x<y ? x : y;}
  #define fmax CASADI_PREFIX(fmax)
  casadi_real fmax(casadi_real x, casadi_real y) { return x>y ? x : y;}
#endif

/* CasADi extensions */
#define sq CASADI_PREFIX(sq)
casadi_real sq(casadi_real x) { return x*x;}
#define sign CASADI_PREFIX(sign)
casadi_real CASADI_PREFIX(sign)(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define twice CASADI_PREFIX(twice)
casadi_real twice(casadi_real x) { return x+x;}
#define if_else CASADI_PREFIX(if_else)
casadi_real if_else(casadi_real c, casadi_real x, casadi_real y) { return c!=0 ? x : y;}

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Printing routine */
#define PRINTF printf

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const int casadi_s1[5] = {1, 1, 0, 1, 0};
static const int casadi_s2[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};

/* adjFun:(i0[4],i1[4],i2)->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0] ? arg[0][1] : 0;
  a1=cos(a0);
  a2=9.8100000000000005e+00;
  a3=arg[1] ? arg[1][3] : 0;
  a4=8.0000000000000004e-01;
  a5=1.1000000000000001e+00;
  a6=1.0000000000000001e-01;
  a7=cos(a0);
  a8=sq(a7);
  a8=(a6*a8);
  a8=(a5-a8);
  a8=(a4*a8);
  a9=(a3/a8);
  a10=(a2*a9);
  a1=(a1*a10);
  a10=sin(a0);
  a7=(a7+a7);
  a11=-8.0000000000000016e-02;
  a12=cos(a0);
  a12=(a11*a12);
  a13=sin(a0);
  a14=(a12*a13);
  a15=arg[0] ? arg[0][3] : 0;
  a16=sq(a15);
  a17=(a14*a16);
  a18=arg[2] ? arg[2][0] : 0;
  a19=cos(a0);
  a20=(a18*a19);
  a17=(a17+a20);
  a20=9.8100000000000009e-01;
  a21=sin(a0);
  a21=(a20*a21);
  a17=(a17+a21);
  a21=sin(a0);
  a2=(a2*a21);
  a17=(a17+a2);
  a17=(a17/a8);
  a17=(a17/a8);
  a17=(a17*a3);
  a4=(a4*a17);
  a4=(a6*a4);
  a7=(a7*a4);
  a10=(a10*a7);
  a1=(a1-a10);
  a10=cos(a0);
  a7=(a20*a9);
  a10=(a10*a7);
  a1=(a1+a10);
  a10=sin(a0);
  a7=(a18*a9);
  a10=(a10*a7);
  a1=(a1-a10);
  a10=cos(a0);
  a16=(a16*a9);
  a12=(a12*a16);
  a10=(a10*a12);
  a1=(a1+a10);
  a10=sin(a0);
  a13=(a13*a16);
  a13=(a11*a13);
  a10=(a10*a13);
  a1=(a1-a10);
  a10=sin(a0);
  a13=cos(a0);
  a16=(a13+a13);
  a12=sin(a0);
  a12=(a11*a12);
  a7=sq(a15);
  a4=(a12*a7);
  a4=(a4+a18);
  a18=cos(a0);
  a18=(a20*a18);
  a17=sin(a0);
  a3=(a18*a17);
  a4=(a4+a3);
  a13=sq(a13);
  a13=(a6*a13);
  a5=(a5-a13);
  a4=(a4/a5);
  a4=(a4/a5);
  a13=arg[1] ? arg[1][2] : 0;
  a4=(a4*a13);
  a6=(a6*a4);
  a16=(a16*a6);
  a10=(a10*a16);
  a1=(a1-a10);
  a10=cos(a0);
  a13=(a13/a5);
  a18=(a18*a13);
  a10=(a10*a18);
  a1=(a1+a10);
  a10=sin(a0);
  a17=(a17*a13);
  a20=(a20*a17);
  a10=(a10*a20);
  a1=(a1-a10);
  a0=cos(a0);
  a7=(a7*a13);
  a11=(a11*a7);
  a0=(a0*a11);
  a1=(a1+a0);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[1] ? arg[1][0] : 0;
  if (res[0]!=0) res[0][2]=a1;
  a1=(a15+a15);
  a14=(a14*a9);
  a1=(a1*a14);
  a15=(a15+a15);
  a12=(a12*a13);
  a15=(a15*a12);
  a1=(a1+a15);
  a15=arg[1] ? arg[1][1] : 0;
  a1=(a1+a15);
  if (res[0]!=0) res[0][3]=a1;
  a19=(a19*a9);
  a19=(a19+a13);
  if (res[0]!=0) res[0][4]=a19;
  return 0;
}

CASADI_SYMBOL_EXPORT int adjFun(const casadi_real** arg, casadi_real** res, int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void adjFun_incref(void) {
}

CASADI_SYMBOL_EXPORT void adjFun_decref(void) {
}

CASADI_SYMBOL_EXPORT int adjFun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT int adjFun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* adjFun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* adjFun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adjFun_sparsity_in(int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const int* adjFun_sparsity_out(int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int adjFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 22;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
