/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) jac_constraint_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[8] = {4, 1, 0, 4, 0, 1, 2, 3};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[5] = {1, 1, 0, 1, 0};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[6] = {2, 1, 0, 2, 0, 1};
#define s2 CASADI_PREFIX(s2)
static const int CASADI_PREFIX(s3)[15] = {2, 4, 0, 2, 4, 6, 8, 0, 1, 0, 1, 0, 1, 0, 1};
#define s3 CASADI_PREFIX(s3)
/* jac_constraint */
int jac_constraint(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=arg[0] ? arg[0][2] : 0;
  real_t a1=sin(a0);
  real_t a2=8.0000000000000004e-01;
  a1=(a2*a1);
  real_t a3=arg[0] ? arg[0][0] : 0;
  a3=(a3-a1);
  a3=(a3-a2);
  if (res[0]!=0) res[0][0]=a3;
  a3=cos(a0);
  a3=(a2*a3);
  a3=(a3-a2);
  if (res[0]!=0) res[0][1]=a3;
  a3=1.;
  if (res[1]!=0) res[1][0]=a3;
  a3=0.;
  if (res[1]!=0) res[1][1]=a3;
  if (res[1]!=0) res[1][2]=a3;
  if (res[1]!=0) res[1][3]=a3;
  a1=cos(a0);
  a1=(a2*a1);
  a1=(-a1);
  if (res[1]!=0) res[1][4]=a1;
  a0=sin(a0);
  a2=(a2*a0);
  a2=(-a2);
  if (res[1]!=0) res[1][5]=a2;
  if (res[1]!=0) res[1][6]=a3;
  if (res[1]!=0) res[1][7]=a3;
  return 0;
}

void jac_constraint_incref(void) {
}

void jac_constraint_decref(void) {
}

int jac_constraint_n_in(void) { return 2;}

int jac_constraint_n_out(void) { return 2;}

const char* jac_constraint_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* jac_constraint_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const int* jac_constraint_sparsity_in(int i) {
  switch (i) {
    case 0: return s0;
    case 1: return s1;
    default: return 0;
  }
}

const int* jac_constraint_sparsity_out(int i) {
  switch (i) {
    case 0: return s2;
    case 1: return s3;
    default: return 0;
  }
}

int jac_constraint_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 4;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
