/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) jac_pendulum_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[8] = {4, 1, 0, 4, 0, 1, 2, 3};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[5] = {1, 1, 0, 1, 0};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
#define s2 CASADI_PREFIX(s2)
/* jacFun */
int jacFun(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=arg[0] ? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0] ? arg[0][2] : 0;
  real_t a1=sin(a0);
  real_t a2=-8.0000000000000016e-02;
  a1=(a2*a1);
  real_t a3=arg[0] ? arg[0][3] : 0;
  real_t a4=(a1*a3);
  real_t a5=(a4*a3);
  real_t a6=cos(a0);
  real_t a7=9.8100000000000009e-01;
  a6=(a7*a6);
  real_t a8=sin(a0);
  real_t a9=(a6*a8);
  a5=(a5+a9);
  a9=arg[1] ? arg[1][0] : 0;
  a5=(a5+a9);
  real_t a10=cos(a0);
  real_t a11=1.0000000000000001e-01;
  a10=(a11*a10);
  real_t a12=cos(a0);
  real_t a13=(a10*a12);
  real_t a14=1.1000000000000001e+00;
  a14=(a14-a13);
  a5=(a5/a14);
  if (res[0]!=0) res[0][1]=a5;
  if (res[0]!=0) res[0][2]=a3;
  a13=cos(a0);
  a13=(a2*a13);
  real_t a15=sin(a0);
  real_t a16=(a13*a15);
  real_t a17=(a16*a3);
  real_t a18=(a17*a3);
  real_t a19=cos(a0);
  a19=(a9*a19);
  a18=(a18+a19);
  a19=sin(a0);
  real_t a20=1.0791000000000002e+01;
  a19=(a20*a19);
  a18=(a18+a19);
  a19=8.0000000000000004e-01;
  real_t a21=(a19*a14);
  a18=(a18/a21);
  if (res[0]!=0) res[0][3]=a18;
  real_t a22=0.;
  if (res[1]!=0) res[1][0]=a22;
  if (res[1]!=0) res[1][1]=a22;
  if (res[1]!=0) res[1][2]=a22;
  if (res[1]!=0) res[1][3]=a22;
  real_t a23=1.;
  if (res[1]!=0) res[1][4]=a23;
  if (res[1]!=0) res[1][5]=a22;
  if (res[1]!=0) res[1][6]=a22;
  if (res[1]!=0) res[1][7]=a22;
  if (res[1]!=0) res[1][8]=a22;
  real_t a24=cos(a0);
  a24=(a2*a24);
  a24=(a3*a24);
  a24=(a3*a24);
  real_t a25=cos(a0);
  a6=(a6*a25);
  a25=sin(a0);
  a7=(a7*a25);
  a8=(a8*a7);
  a6=(a6-a8);
  a24=(a24+a6);
  a24=(a24/a14);
  a5=(a5/a14);
  a6=sin(a0);
  a11=(a11*a6);
  a12=(a12*a11);
  a11=sin(a0);
  a10=(a10*a11);
  a12=(a12+a10);
  a5=(a5*a12);
  a24=(a24-a5);
  if (res[1]!=0) res[1][9]=a24;
  if (res[1]!=0) res[1][10]=a22;
  a24=cos(a0);
  a13=(a13*a24);
  a24=sin(a0);
  a2=(a2*a24);
  a15=(a15*a2);
  a13=(a13-a15);
  a13=(a3*a13);
  a13=(a3*a13);
  a15=sin(a0);
  a9=(a9*a15);
  a13=(a13-a9);
  a0=cos(a0);
  a20=(a20*a0);
  a13=(a13+a20);
  a13=(a13/a21);
  a18=(a18/a21);
  a19=(a19*a12);
  a18=(a18*a19);
  a13=(a13-a18);
  if (res[1]!=0) res[1][11]=a13;
  if (res[1]!=0) res[1][12]=a22;
  a1=(a3*a1);
  a1=(a1+a4);
  a1=(a1/a14);
  if (res[1]!=0) res[1][13]=a1;
  if (res[1]!=0) res[1][14]=a23;
  a3=(a3*a16);
  a3=(a3+a17);
  a3=(a3/a21);
  if (res[1]!=0) res[1][15]=a3;
  return 0;
}

void jacFun_incref(void) {
}

void jacFun_decref(void) {
}

int jacFun_n_in(void) { return 2;}

int jacFun_n_out(void) { return 2;}

const char* jacFun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* jacFun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const int* jacFun_sparsity_in(int i) {
  switch (i) {
    case 0: return s0;
    case 1: return s1;
    default: return 0;
  }
}

const int* jacFun_sparsity_out(int i) {
  switch (i) {
    case 0: return s0;
    case 1: return s2;
    default: return 0;
  }
}

int jacFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 26;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
