/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef real_t
#define real_t double
#endif /* real_t */

int vdeFun(const real_t** arg, real_t** res, int* iw, real_t* w, int mem);
void vdeFun_incref(void);
void vdeFun_decref(void);
int vdeFun_n_in(void);
int vdeFun_n_out(void);
const char* vdeFun_name_in(int i);
const char* vdeFun_name_out(int i);
const int* vdeFun_sparsity_in(int i);
const int* vdeFun_sparsity_out(int i);
int vdeFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
