/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) vde_forw_pendulum_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
#define CASADI_CAST(x,y) (x) y
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[8] = {4, 1, 0, 4, 0, 1, 2, 3};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[5] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
/* vdeFun */
int vdeFun(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=arg[0] ? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0] ? arg[0][2] : 0;
  real_t a1=sin(a0);
  real_t a2=-8.0000000000000016e-02;
  a1=(a2*a1);
  real_t a3=arg[0] ? arg[0][3] : 0;
  real_t a4=(a1*a3);
  real_t a5=(a4*a3);
  real_t a6=cos(a0);
  real_t a7=9.8100000000000009e-01;
  a6=(a7*a6);
  real_t a8=sin(a0);
  real_t a9=(a6*a8);
  a5=(a5+a9);
  a9=arg[3] ? arg[3][0] : 0;
  a5=(a5+a9);
  real_t a10=cos(a0);
  real_t a11=1.0000000000000001e-01;
  a10=(a11*a10);
  real_t a12=cos(a0);
  real_t a13=(a10*a12);
  real_t a14=1.1000000000000001e+00;
  a14=(a14-a13);
  a5=(a5/a14);
  if (res[0]!=0) res[0][1]=a5;
  if (res[0]!=0) res[0][2]=a3;
  a13=cos(a0);
  a13=(a2*a13);
  real_t a15=sin(a0);
  real_t a16=(a13*a15);
  real_t a17=(a16*a3);
  real_t a18=(a17*a3);
  real_t a19=cos(a0);
  real_t a20=(a9*a19);
  a18=(a18+a20);
  a20=sin(a0);
  real_t a21=1.0791000000000002e+01;
  a20=(a21*a20);
  a18=(a18+a20);
  a20=8.0000000000000004e-01;
  real_t a22=(a20*a14);
  a18=(a18/a22);
  if (res[0]!=0) res[0][3]=a18;
  real_t a23=arg[1] ? arg[1][1] : 0;
  if (res[1]!=0) res[1][0]=a23;
  a23=cos(a0);
  real_t a24=arg[1] ? arg[1][2] : 0;
  real_t a25=(a23*a24);
  a25=(a2*a25);
  a25=(a3*a25);
  real_t a26=arg[1] ? arg[1][3] : 0;
  real_t a27=(a1*a26);
  a25=(a25+a27);
  a25=(a3*a25);
  a27=(a4*a26);
  a25=(a25+a27);
  a27=cos(a0);
  real_t a28=(a27*a24);
  a28=(a6*a28);
  real_t a29=sin(a0);
  real_t a30=(a29*a24);
  a30=(a7*a30);
  a30=(a8*a30);
  a28=(a28-a30);
  a25=(a25+a28);
  a25=(a25/a14);
  a28=(a5/a14);
  a30=sin(a0);
  real_t a31=(a30*a24);
  a31=(a11*a31);
  a31=(a12*a31);
  real_t a32=sin(a0);
  real_t a33=(a32*a24);
  a33=(a10*a33);
  a31=(a31+a33);
  a33=(a28*a31);
  a25=(a25-a33);
  if (res[1]!=0) res[1][1]=a25;
  if (res[1]!=0) res[1][2]=a26;
  a25=cos(a0);
  a33=(a25*a24);
  a33=(a13*a33);
  real_t a34=sin(a0);
  real_t a35=(a34*a24);
  a35=(a2*a35);
  a35=(a15*a35);
  a33=(a33-a35);
  a33=(a3*a33);
  a35=(a16*a26);
  a33=(a33+a35);
  a33=(a3*a33);
  a26=(a17*a26);
  a33=(a33+a26);
  a26=sin(a0);
  a35=(a26*a24);
  a35=(a9*a35);
  a33=(a33-a35);
  a35=cos(a0);
  a24=(a35*a24);
  a24=(a21*a24);
  a33=(a33+a24);
  a33=(a33/a22);
  a24=(a18/a22);
  a31=(a20*a31);
  a31=(a24*a31);
  a33=(a33-a31);
  if (res[1]!=0) res[1][3]=a33;
  a33=arg[1] ? arg[1][5] : 0;
  if (res[1]!=0) res[1][4]=a33;
  a33=arg[1] ? arg[1][6] : 0;
  a31=(a23*a33);
  a31=(a2*a31);
  a31=(a3*a31);
  real_t a36=arg[1] ? arg[1][7] : 0;
  real_t a37=(a1*a36);
  a31=(a31+a37);
  a31=(a3*a31);
  a37=(a4*a36);
  a31=(a31+a37);
  a37=(a27*a33);
  a37=(a6*a37);
  real_t a38=(a29*a33);
  a38=(a7*a38);
  a38=(a8*a38);
  a37=(a37-a38);
  a31=(a31+a37);
  a31=(a31/a14);
  a37=(a30*a33);
  a37=(a11*a37);
  a37=(a12*a37);
  a38=(a32*a33);
  a38=(a10*a38);
  a37=(a37+a38);
  a38=(a28*a37);
  a31=(a31-a38);
  if (res[1]!=0) res[1][5]=a31;
  if (res[1]!=0) res[1][6]=a36;
  a31=(a25*a33);
  a31=(a13*a31);
  a38=(a34*a33);
  a38=(a2*a38);
  a38=(a15*a38);
  a31=(a31-a38);
  a31=(a3*a31);
  a38=(a16*a36);
  a31=(a31+a38);
  a31=(a3*a31);
  a36=(a17*a36);
  a31=(a31+a36);
  a36=(a26*a33);
  a36=(a9*a36);
  a31=(a31-a36);
  a33=(a35*a33);
  a33=(a21*a33);
  a31=(a31+a33);
  a31=(a31/a22);
  a37=(a20*a37);
  a37=(a24*a37);
  a31=(a31-a37);
  if (res[1]!=0) res[1][7]=a31;
  a31=arg[1] ? arg[1][9] : 0;
  if (res[1]!=0) res[1][8]=a31;
  a31=arg[1] ? arg[1][10] : 0;
  a37=(a23*a31);
  a37=(a2*a37);
  a37=(a3*a37);
  a33=arg[1] ? arg[1][11] : 0;
  a36=(a1*a33);
  a37=(a37+a36);
  a37=(a3*a37);
  a36=(a4*a33);
  a37=(a37+a36);
  a36=(a27*a31);
  a36=(a6*a36);
  a38=(a29*a31);
  a38=(a7*a38);
  a38=(a8*a38);
  a36=(a36-a38);
  a37=(a37+a36);
  a37=(a37/a14);
  a36=(a30*a31);
  a36=(a11*a36);
  a36=(a12*a36);
  a38=(a32*a31);
  a38=(a10*a38);
  a36=(a36+a38);
  a38=(a28*a36);
  a37=(a37-a38);
  if (res[1]!=0) res[1][9]=a37;
  if (res[1]!=0) res[1][10]=a33;
  a37=(a25*a31);
  a37=(a13*a37);
  a38=(a34*a31);
  a38=(a2*a38);
  a38=(a15*a38);
  a37=(a37-a38);
  a37=(a3*a37);
  a38=(a16*a33);
  a37=(a37+a38);
  a37=(a3*a37);
  a33=(a17*a33);
  a37=(a37+a33);
  a33=(a26*a31);
  a33=(a9*a33);
  a37=(a37-a33);
  a31=(a35*a31);
  a31=(a21*a31);
  a37=(a37+a31);
  a37=(a37/a22);
  a36=(a20*a36);
  a36=(a24*a36);
  a37=(a37-a36);
  if (res[1]!=0) res[1][11]=a37;
  a37=arg[1] ? arg[1][13] : 0;
  if (res[1]!=0) res[1][12]=a37;
  a37=arg[1] ? arg[1][14] : 0;
  a23=(a23*a37);
  a23=(a2*a23);
  a23=(a3*a23);
  a36=arg[1] ? arg[1][15] : 0;
  a31=(a1*a36);
  a23=(a23+a31);
  a23=(a3*a23);
  a31=(a4*a36);
  a23=(a23+a31);
  a27=(a27*a37);
  a27=(a6*a27);
  a29=(a29*a37);
  a29=(a7*a29);
  a29=(a8*a29);
  a27=(a27-a29);
  a23=(a23+a27);
  a23=(a23/a14);
  a30=(a30*a37);
  a30=(a11*a30);
  a30=(a12*a30);
  a32=(a32*a37);
  a32=(a10*a32);
  a30=(a30+a32);
  a28=(a28*a30);
  a23=(a23-a28);
  if (res[1]!=0) res[1][13]=a23;
  if (res[1]!=0) res[1][14]=a36;
  a25=(a25*a37);
  a25=(a13*a25);
  a34=(a34*a37);
  a34=(a2*a34);
  a34=(a15*a34);
  a25=(a25-a34);
  a25=(a3*a25);
  a34=(a16*a36);
  a25=(a25+a34);
  a25=(a3*a25);
  a36=(a17*a36);
  a25=(a25+a36);
  a26=(a26*a37);
  a26=(a9*a26);
  a25=(a25-a26);
  a35=(a35*a37);
  a35=(a21*a35);
  a25=(a25+a35);
  a25=(a25/a22);
  a30=(a20*a30);
  a24=(a24*a30);
  a25=(a25-a24);
  if (res[1]!=0) res[1][15]=a25;
  a25=arg[2] ? arg[2][1] : 0;
  if (res[2]!=0) res[2][0]=a25;
  a25=cos(a0);
  a24=arg[2] ? arg[2][2] : 0;
  a25=(a25*a24);
  a25=(a2*a25);
  a25=(a3*a25);
  a30=arg[2] ? arg[2][3] : 0;
  a1=(a1*a30);
  a25=(a25+a1);
  a25=(a3*a25);
  a4=(a4*a30);
  a25=(a25+a4);
  a4=cos(a0);
  a4=(a4*a24);
  a6=(a6*a4);
  a4=sin(a0);
  a4=(a4*a24);
  a7=(a7*a4);
  a8=(a8*a7);
  a6=(a6-a8);
  a25=(a25+a6);
  a25=(a25/a14);
  a5=(a5/a14);
  a6=sin(a0);
  a6=(a6*a24);
  a11=(a11*a6);
  a12=(a12*a11);
  a11=sin(a0);
  a11=(a11*a24);
  a10=(a10*a11);
  a12=(a12+a10);
  a5=(a5*a12);
  a25=(a25-a5);
  a14=(1./a14);
  a14=(a14+a25);
  if (res[2]!=0) res[2][1]=a14;
  if (res[2]!=0) res[2][2]=a30;
  a19=(a19/a22);
  a14=cos(a0);
  a14=(a14*a24);
  a13=(a13*a14);
  a14=sin(a0);
  a14=(a14*a24);
  a2=(a2*a14);
  a15=(a15*a2);
  a13=(a13-a15);
  a13=(a3*a13);
  a16=(a16*a30);
  a13=(a13+a16);
  a3=(a3*a13);
  a17=(a17*a30);
  a3=(a3+a17);
  a17=sin(a0);
  a17=(a17*a24);
  a9=(a9*a17);
  a3=(a3-a9);
  a0=cos(a0);
  a0=(a0*a24);
  a21=(a21*a0);
  a3=(a3+a21);
  a3=(a3/a22);
  a18=(a18/a22);
  a20=(a20*a12);
  a18=(a18*a20);
  a3=(a3-a18);
  a19=(a19+a3);
  if (res[2]!=0) res[2][3]=a19;
  return 0;
}

void vdeFun_incref(void) {
}

void vdeFun_decref(void) {
}

int vdeFun_n_in(void) { return 4;}

int vdeFun_n_out(void) { return 3;}

const char* vdeFun_name_in(int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

const char* vdeFun_name_out(int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

const int* vdeFun_sparsity_in(int i) {
  switch (i) {
    case 0: return s0;
    case 1: return s1;
    case 2: return s0;
    case 3: return s2;
    default: return 0;
  }
}

const int* vdeFun_sparsity_out(int i) {
  switch (i) {
    case 0: return s0;
    case 1: return s1;
    case 2: return s0;
    default: return 0;
  }
}

int vdeFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 39;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
