/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef real_t
#define real_t double
#endif /* real_t */

int adjFun(const real_t** arg, real_t** res, int* iw, real_t* w, int mem);
void adjFun_incref(void);
void adjFun_decref(void);
int adjFun_n_in(void);
int adjFun_n_out(void);
const char* adjFun_name_in(int i);
const char* adjFun_name_out(int i);
const int* adjFun_sparsity_in(int i);
const int* adjFun_sparsity_out(int i);
int adjFun_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
