/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) impl_jac_xdot_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[6] = {2, 1, 0, 2, 0, 1};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
#define s2 CASADI_PREFIX(s2)
/* impl_jacFun_xdot */
int impl_jacFun_xdot(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=1.;
  if (res[0]!=0) res[0][0]=a0;
  real_t a1=0.;
  if (res[0]!=0) res[0][1]=a1;
  if (res[0]!=0) res[0][2]=a1;
  if (res[0]!=0) res[0][3]=a1;
  if (res[0]!=0) res[0][4]=a1;
  if (res[0]!=0) res[0][5]=a1;
  if (res[0]!=0) res[0][6]=a1;
  if (res[0]!=0) res[0][7]=a0;
  if (res[0]!=0) res[0][8]=a1;
  if (res[0]!=0) res[0][9]=a1;
  if (res[0]!=0) res[0][10]=a1;
  if (res[0]!=0) res[0][11]=a1;
  if (res[0]!=0) res[0][12]=a1;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a0;
  if (res[0]!=0) res[0][15]=a1;
  if (res[0]!=0) res[0][16]=a1;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a1;
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a1;
  if (res[0]!=0) res[0][21]=a0;
  if (res[0]!=0) res[0][22]=a1;
  if (res[0]!=0) res[0][23]=a1;
  if (res[0]!=0) res[0][24]=a1;
  if (res[0]!=0) res[0][25]=a1;
  if (res[0]!=0) res[0][26]=a1;
  if (res[0]!=0) res[0][27]=a1;
  if (res[0]!=0) res[0][28]=a0;
  if (res[0]!=0) res[0][29]=a1;
  if (res[0]!=0) res[0][30]=a1;
  if (res[0]!=0) res[0][31]=a1;
  if (res[0]!=0) res[0][32]=a1;
  if (res[0]!=0) res[0][33]=a1;
  if (res[0]!=0) res[0][34]=a1;
  if (res[0]!=0) res[0][35]=a0;
  return 0;
}

void impl_jacFun_xdot_incref(void) {
}

void impl_jacFun_xdot_decref(void) {
}

int impl_jacFun_xdot_n_in(void) { return 3;}

int impl_jacFun_xdot_n_out(void) { return 1;}

const char* impl_jacFun_xdot_name_in(int i){
  switch (i) {
  case 0: return "i0";
  case 1: return "i1";
  case 2: return "i2";
  default: return 0;
  }
}

const char* impl_jacFun_xdot_name_out(int i){
  switch (i) {
  case 0: return "o0";
  default: return 0;
  }
}

const int* impl_jacFun_xdot_sparsity_in(int i) {
  switch (i) {
  case 0: return s0;
  case 1: return s0;
  case 2: return s1;
  default: return 0;
  }
}

const int* impl_jacFun_xdot_sparsity_out(int i) {
  switch (i) {
  case 0: return s2;
  default: return 0;
  }
}

int impl_jacFun_xdot_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
