# Author Gianluca Frison

include ../../Makefile.rule

OBJS =

OBJS += dense_qp_common.o
OBJS += dense_qp_common_ext_dep.o
OBJS += dense_qp_hpipm.o
OBJS += dense_qp_hpipm_ext_dep.o
OBJS += dense_qp_qpoases.o
OBJS += dense_qp_qpoases_ext_dep.o

obj: $(OBJS)

clean:
	rm -f *.o
	rm -f *.s
