/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) expl_vde_for_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {4, 0, 0};
static const casadi_int casadi_s3[4] = {0, 1, 0, 0};

/* expl_vde_for:(i0[4],i1[4x4],i2[4x0],i3[0])->(o0[4],o1[4x4],o2[4x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1;
  a0=-2.;
  a1=arg[0] ? arg[0][0] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][0]=a1;
  a1=arg[0] ? arg[0][1] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][1]=a1;
  a1=arg[0] ? arg[0][2] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[0] ? arg[0][3] : 0;
  a1=(a0*a1);
  if (res[0]!=0) res[0][3]=a1;
  a1=arg[1] ? arg[1][0] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][0]=a1;
  a1=arg[1] ? arg[1][1] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][1]=a1;
  a1=arg[1] ? arg[1][2] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][2]=a1;
  a1=arg[1] ? arg[1][3] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][3]=a1;
  a1=arg[1] ? arg[1][4] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][4]=a1;
  a1=arg[1] ? arg[1][5] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][5]=a1;
  a1=arg[1] ? arg[1][6] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][6]=a1;
  a1=arg[1] ? arg[1][7] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][7]=a1;
  a1=arg[1] ? arg[1][8] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][8]=a1;
  a1=arg[1] ? arg[1][9] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][9]=a1;
  a1=arg[1] ? arg[1][10] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][10]=a1;
  a1=arg[1] ? arg[1][11] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][11]=a1;
  a1=arg[1] ? arg[1][12] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][12]=a1;
  a1=arg[1] ? arg[1][13] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][13]=a1;
  a1=arg[1] ? arg[1][14] : 0;
  a1=(a0*a1);
  if (res[1]!=0) res[1][14]=a1;
  a1=arg[1] ? arg[1][15] : 0;
  a0=(a0*a1);
  if (res[1]!=0) res[1][15]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int expl_vde_for(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void expl_vde_for_incref(void) {
}

CASADI_SYMBOL_EXPORT void expl_vde_for_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int expl_vde_for_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int expl_vde_for_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT const char* expl_vde_for_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* expl_vde_for_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* expl_vde_for_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* expl_vde_for_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int expl_vde_for_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
