SOURCES = [ 'acados_solver_sfunction_{{ model.name }}.c ', ...
            'acados_solver_{{ model.name }}.c ', ...
            {%- if  solver_config.integrator_type == 'ERK' %}
            '{{ model.name }}_model/{{ model.name }}_expl_ode_fun.c ', ...
            '{{ model.name }}_model/{{ model.name }}_expl_vde_forw.c ',...
            {% if solver_config.hessian_approx == 'EXACT' -%} 
            {% endif -%}
            {% else %}
            '{{ model.name }}_model/{{ model.name }}_impl_dae_fun.c ', ...
            '{{ model.name }}_model/{{ model.name }}_impl_dae_fun_jac_x_xdot_z.c ', ...
            '{{ model.name }}_model/{{ model.name }}_impl_dae_jac_x_xdot_u_z.c ', ...
            {% endif -%}
            {% if dims.npd > 0 -%}
            '{{ con_p.name }}_p_constraint/{{ con_p.name }}_p_constraint.c ', ...
            {% endif -%}
            {% if dims.nh > 0 -%}
            '{{ con_h.name }}_h_constraint/{{ con_h.name }}_h_constraint.c ', ...
            {% endif -%}
          ];

INC_PATH = '{{ acados_include_path }}';

INCS = [ ' -I', INC_PATH, '/blasfeo/include/ ', ...
          '-I', INC_PATH, ' -I', INC_PATH, '/acados/ ', ...
          '-I', INC_PATH, '/qpOASES_e/' ];

CFLAGS  = ' -O';

{% if  solver_config.qp_solver == "QPOASES" %}
CFLAGS = [ CFLAGS, ' -DACADOS_WITH_QPOASES ' ];
{% endif %}

LIB_PATH = '{{ acados_lib_path }}';

LIBS = '-lacados -lhpipm -lblasfeo -lqpOASES_e -lm'; 
    
eval( [ 'mex -v -output  acados_solver_sfunction_{{ model.name }} ', ...
    CFLAGS, INCS, ' ', SOURCES, ' -L', LIB_PATH, ' ', LIBS ]);

disp( [ 'acados_solver_sfunction_{{ model.name }}', '.', ...
    eval('mexext'), ' successfully created!'] );
