/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
  #define CASADI_PREFIX(ID) discrete_model_cost_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#ifndef real_t
#define real_t double
#endif /* real_t */

#define to_double(x) (double) x
#define to_int(x) (int) x
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
real_t CASADI_PREFIX(fmin)(real_t x, real_t y) { return x<y ? x : y;}
#define fmin(x,y) CASADI_PREFIX(fmin)(x,y)
real_t CASADI_PREFIX(fmax)(real_t x, real_t y) { return x>y ? x : y;}
#define fmax(x,y) CASADI_PREFIX(fmax)(x,y)
#endif

#define PRINTF printf
real_t CASADI_PREFIX(sq)(real_t x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

real_t CASADI_PREFIX(sign)(real_t x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const int CASADI_PREFIX(s0)[5] = {1, 1, 0, 1, 0};
#define s0 CASADI_PREFIX(s0)
static const int CASADI_PREFIX(s1)[6] = {2, 1, 0, 2, 0, 1};
#define s1 CASADI_PREFIX(s1)
static const int CASADI_PREFIX(s2)[7] = {2, 2, 0, 1, 2, 0, 1};
#define s2 CASADI_PREFIX(s2)
/* discrete_model_cost */
int discrete_model_cost(const real_t** arg, real_t** res, int* iw, real_t* w, int mem) {
  real_t a0=arg[0] ? arg[0][0] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[1] ? arg[1][0] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=1.;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  return 0;
}

void discrete_model_cost_incref(void) {
}

void discrete_model_cost_decref(void) {
}

int discrete_model_cost_n_in(void) { return 2;}

int discrete_model_cost_n_out(void) { return 2;}

const char* discrete_model_cost_name_in(int i){
  switch (i) {
  case 0: return "i0";
  case 1: return "i1";
  default: return 0;
  }
}

const char* discrete_model_cost_name_out(int i){
  switch (i) {
  case 0: return "o0";
  case 1: return "o1";
  default: return 0;
  }
}

const int* discrete_model_cost_sparsity_in(int i) {
  switch (i) {
  case 0: return s0;
  case 1: return s0;
  default: return 0;
  }
}

const int* discrete_model_cost_sparsity_out(int i) {
  switch (i) {
  case 0: return s1;
  case 1: return s2;
  default: return 0;
  }
}

int discrete_model_cost_work(int *sz_arg, int* sz_res, int *sz_iw, int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
