name: Test ROS2 Build Linux

on:
  push:
    branches-ignore:
      - 'doc*'
      - 'wip*'
  pull_request:
    branches:
      - '*'

jobs:
  call_core_build:
    uses: ./.github/workflows/core_build.yml

  ros2_humble_test:
    needs: call_core_build
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          submodules: 'recursive'
        
    - name: Cache ROS installation
      uses: actions/cache@v4
      with:
        path: /opt/ros/humble
        key: ${{ runner.os }}-ros-humble-${{ hashFiles('.github/linux/install_ros2_humble.sh') }}
      
    - name: Install ROS2 Humble
      working-directory: ${{ github.workspace }}
      run: ${{ github.workspace }}/.github/linux/install_ros2_humble.sh
      shell: bash

    - name: Install System Dependencies
      uses: ./.github/actions/setup-system-dependencies

    - name: Setup Test Environment
      uses: ./.github/actions/setup-test-environment
      with:
        artifact-name-prefix: ${{ needs.call_core_build.outputs.artifact-name-prefix }}

    - name: Setup Python Environment
      uses: ./.github/actions/setup-python-environment
      
    - name: Test ROS2 Packages
      uses: ./.github/actions/test-ros2-package
      with:
        python-file-path: ${{ github.workspace }}/examples/acados_python/pendulum_on_cart/ros2/example_ros_sqp_rti_loop.py
        source-paths: |
          '${{ github.workspace }}/examples/acados_python/pendulum_on_cart/common/pendulum_model.py'