name: Test ROS2 Build Linux

on:
  push:
    branches-ignore:
      - 'doc*'
      - 'wip*'
  pull_request:
    branches:
      - '*'

jobs:
  call_core_build:
    uses: ./.github/workflows/core_build.yml

  ros2_humble_test:
    needs: call_core_build
    runs-on: ubuntu-22.04

    container:
      image: osrf/ros:humble-desktop

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - uses: actions/download-artifact@v4
      with:
        path: ${{ github.workspace }}

    - name: Export Paths
      working-directory: ${{ github.workspace }}
      shell: bash
      run: |
        ${{ github.workspace }}/.github/linux/export_paths.sh ${{ github.workspace }}

    - name: Install Python interface
      working-directory: ${{ github.workspace }}
      shell: bash
      run: ${{ github.workspace }}/.github/linux/install_python.sh

    - name: Install Tera
      working-directory: ${{ github.workspace }}
      shell: bash
      run: ${{ github.workspace }}/.github/linux/install_tera.sh

    - name: Run Cart Pendulum Ros2 smoke tests
      working-directory: ${{ github.workspace }}/examples/acados_python/pendulum_on_cart/ros2
      shell: bash
      run: |
        source ${{ github.workspace }}/acadosenv/bin/activate
        python example_ros_sqp_rti_loop.py
        echo "\nTesting OCP ROS2 Humble\n"
        source /opt/ros/humble/setup.bash

        # small isolated build environment
        WS=${{ github.workspace }}/ros_pendulum_ws
        mkdir -p $WS/src
        rsync -a . $WS/src/pendulum_on_cart

        cd $WS
        rosdep update || true
        rosdep install --from-paths src --ignore-src -r -y || true

        colcon build --packages-select pendulum_on_cart pendulum_on_cart_interface
        source install/setup.bash

        echo "Start Node (8s Timeout)"
        timeout 8s ros2 run pendulum_on_cart pendulum_on_cart_node || EXIT_CODE=$?
        if [ "${EXIT_CODE:-0}" != "0" ] && [ "${EXIT_CODE:-0}" != "124" ]; then
          echo "Node feilure: Exit-Code ${EXIT_CODE}"
          exit 1
        fi

        if [ "${EXIT_CODE:-0}" = "124" ]; then
          echo "Test passed!"
        else
          echo "Test failed: Node exited before Timeout (Exit-Code ${EXIT_CODE})"
        fi